name: First workflow

# Specify the event that triggers the workflow
on:
  workflow_dispatch:

# Define the jobs
jobs:
  first_job: 
    runs-on: windows-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
        
      - name: Print a Thanks message
        run: echo "Thanks & regards"

      - name: Print multiple messages
        run: |
          echo "First line"
          echo "Second line"
