name: globalVariable
on: workflow_dispatch
env:
    USERNAME: aanujkothari
    password: 12345  
jobs:
    Regression_Testing:
        runs-on: windows-latest
        steps: 
           - name: Print variable
             run: echo ${{env.USER}}

           - name: Print step level variable
             env: 
               city: Delhi
             run: echo ${{env.city}}
             
    # Adhoc_Testing:
    #        runs-on: macos-latest
  
    #        steps: 
    #            - name: Print variable
    #              run: echo ${{env.USER}}

    #        - name: Print step level variable
    #          run: echo ${{env.city}}
