name: secrets
on: workflow_dispatch
jobs:
    using_secret_variables:
        runs-on: ubuntu-latest
        # env:
        #     USER: Anuj
        steps: 
           # - name: Print job level variable
           #   run: echo ${{env.USER}}

           - name: Print first secret variable
             run: echo ${{secrets.SECRET_NAME}}

           - name: Print second secret variable
             run: echo ${{secrets.AGE}}
