name: secrets
on: workflow_dispatch
jobs:
    using-variables:
        runs-on: ubuntu-latest
        env:
            USER: Anuj
        steps: 
           - name: Print variable
             run: echo ${{env.USER}}

           - name: Print step level variable
             env: 
               city: Delhi
             run: echo ${{secrets.USERNAME}}
