name: secrets
on: workflow_dispatch
jobs:
    using_secret_variables:
        runs-on: ubuntu-latest
        env:
            USER: Anuj
        steps: 
           - name: Print variable
             run: echo ${{env.USER}}

           - name: Print first secret variable
             env: 
               city: Delhi
             run: echo ${{secrets.USERNAME}}
