name: Repo level variables
on: workflow_dispatch
jobs:
    Build:
        runs-on: windows-latest
        steps: 
           - name: Print first repo variable 
             run: |
                 echo ${{vars.city}}

           - name: Print step level variable
             env: 
               city: Manali
             run: echo ${{env.city}}
             
    Testing:
        needs: [Build]
        runs-on: macos-latest
        steps: 
            - name: Print second repo variable
              run: |
                  echo ${{vars.continent}}
